language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
install:
  - pip install --allow-external=argparse -e .
  - pip install flake8==2.3.0 mccabe==0.3.0 pep8==1.6.2 pyflakes==0.8.1
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2==0.5.1; fi
  - if [[ $(pip --version | python -c 'import sys; line = sys.stdin.read().splitlines()[0]; print(line.split()[1].split(".", 2)[1])') -le 4 ]]; then pip install -I virtualenv==1.10.1; fi
script:
  - flake8 --statistics *.py
  - python tests.py
  - python setup.py test
matrix:
  allow_failures:
    - python: pypy
